# 3.2 Bokeh (done)

We will not dive deep into Bokeh. We suggest running the following code to see the possibilities of this package. The main difference with seaborn is that it allows for dynamic graphics.

Sample bokeh data is saved in the following location:
    
    /Users/AVNH/.bokeh/data/

In [1]:
#pre-requisites:install the package

#!pip install bokeh

In [2]:
# to make the .py script runnable
#!/usr/bin/env python

In [3]:
from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
plt.style.use('ggplot')

In [4]:
import os
cdir = os.getcwd()
print(cdir)

/Users/AVNH/0 - Crunch Analytics/Notebooks

## 3.2.1 Import Bokeh

In [5]:
import bokeh

from bokeh.io import show
from bokeh.models import (
    ColumnDataSource,
    HoverTool,
    LogColorMapper
)
from bokeh.palettes import Viridis6 as palette
from bokeh.plotting import figure

## 3.2.2 Get the Texas data

The example talks uses data of the state of Texas, which we will download.

In [6]:
import inspect
lines = inspect.getsource(bokeh.sampledata.download)
print(lines)

def download(progress=True):
    ''' Download larger data sets for various Bokeh examples.

    '''
    data_dir = external_data_dir(create=True)
    print("Using data directory: %s" % data_dir)

    s3 = 'https://bokeh-sampledata.s3.amazonaws.com'
    files = [
        (s3, 'CGM.csv'),
        (s3, 'US_Counties.zip'),
        (s3, 'us_cities.json'),
        (s3, 'unemployment09.csv'),
        (s3, 'AAPL.csv'),
        (s3, 'FB.csv'),
        (s3, 'GOOG.csv'),
        (s3, 'IBM.csv'),
        (s3, 'MSFT.csv'),
        (s3, 'WPP2012_SA_DB03_POPULATION_QUINQUENNIAL.zip'),
        (s3, 'gapminder_fertility.csv'),
        (s3, 'gapminder_population.csv'),
        (s3, 'gapminder_life_expectancy.csv'),
        (s3, 'gapminder_regions.csv'),
        (s3, 'world_cities.zip'),
        (s3, 'airports.json'),
        (s3, 'movies.db.zip'),
        (s3, 'airports.csv'),
        (s3, 'routes.csv'),
        (s3, 'haarcascade_frontalface_default.xml'),
    ]

    for base_url, filename in files:
        _download_file(base_url, filename, data_dir, progress=progress)

In [ ]:
def download(progress=True):
    ''' Download larger data sets for various Bokeh examples.

    '''
    data_dir = external_data_dir(create=True)
    print("Using data directory: %s" % data_dir)

    s3 = 'https://bokeh-sampledata.s3.amazonaws.com'
    files = [
        (s3, 'CGM.csv'),
        (s3, 'US_Counties.zip'),
        (s3, 'us_cities.json'),
        (s3, 'unemployment09.csv'),
        (s3, 'AAPL.csv'),
        (s3, 'FB.csv'),
        (s3, 'GOOG.csv'),
        (s3, 'IBM.csv'),
        (s3, 'MSFT.csv'),
        (s3, 'WPP2012_SA_DB03_POPULATION_QUINQUENNIAL.zip'),
        (s3, 'gapminder_fertility.csv'),
        (s3, 'gapminder_population.csv'),
        (s3, 'gapminder_life_expectancy.csv'),
        (s3, 'gapminder_regions.csv'),
        (s3, 'world_cities.zip'),
        (s3, 'airports.json'),
        (s3, 'movies.db.zip'),
        (s3, 'airports.csv'),
        (s3, 'routes.csv'),
        (s3, 'haarcascade_frontalface_default.xml'),
    ]

    for base_url, filename in files:
        _download_file(base_url, filename, data_dir, progress=progress)

In [ ]:
# This requires an internet connection (obviously)
bokeh.sampledata.download()

In [7]:
from bokeh.sampledata.us_counties import data as counties
from bokeh.sampledata.unemployment import data as unemployment

In [8]:
print(type(counties))
df_counties = pd.DataFrame(counties)
df_counties.info()

<class 'dict'>
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, detailed name to state
Columns: 3233 entries, (1, 1) to (78, 30)
dtypes: object(3233)
memory usage: 126.3+ KB

In [9]:
df_counties.head()

                                                              1   \
                                                             1
detailed name                            Autauga County, Alabama
lats           [32.4757, 32.46599, 32.45054, 32.44245, 32.439...
lons           [-86.41182, -86.41177, -86.41167, -86.41157, -...
name                                                     Autauga
state                                                         al

                                                                  \
                                                             3
detailed name                            Baldwin County, Alabama
lats           [30.28557, 30.21934, 30.21771, 30.21183, 30.20...
lons           [-87.51203, -87.56704, -87.5741, -87.59954, -8...
name                                                     Baldwin
state                                                         al

                                                                  \
                                                             5
detailed name                            Barbour County, Alabama
lats           [32.02221, 32.02066, 32.0135, 32.00249, 31.996...
lons           [-85.04884, -85.05367, -85.05381, -85.06454, -...
name                                                     Barbour
state                                                         al

                                                                  \
                                                             7
detailed name                               Bibb County, Alabama
lats           [33.13143, 33.13086, 33.15133, 33.18184, 33.18...
lons           [-87.23637, -87.21582, -87.19914, -87.19907, -...
name                                                        Bibb
state                                                         al

                                                                  \
                                                             9
detailed name                             Blount County, Alabama
lats           [33.949, 33.95621, 33.9629, 33.97324, 33.99538...
lons           [-86.8332, -86.81779, -86.79248, -86.7719, -86...
name                                                      Blount
state                                                         al

                                                                  \
                                                             11
detailed name                            Bullock County, Alabama
lats           [32.27298, 32.27303, 32.27305, 32.27355, 32.27...
lons           [-85.9657, -85.96397, -85.96321, -85.94714, -8...
name                                                     Bullock
state                                                         al

                                                                  \
                                                             13
detailed name                             Butler County, Alabama
lats           [31.72776, 31.75303, 31.76712, 31.77059, 31.78...
lons           [-86.90522, -86.9059, -86.90615, -86.90621, -8...
name                                                      Butler
state                                                         al

                                                                  \
                                                             15
detailed name                            Calhoun County, Alabama
lats           [33.85224, 33.86549, 33.86938, 33.8792, 33.881...
lons           [-86.03745, -86.01168, -85.99517, -85.98747, -...
name                                                     Calhoun
state                                                         al

                                                                  \
                                                             17
detailed name                           Chambers County, Alabama
lats           [32.74111, 32.73073, 32.73041, 32.73043, 32.73...
lons           [-85.28495, -85.31152, -85.36416, -85.38834, -...
name                                                    Chambers
state                                                         al

                                                                  \
                                                             19
detailed name                           Cherokee County, Alabama
lats           [34.50008, 34.51196, 34.51649, 34.52476, 34.52...
lons           [-85.54764, -85.53519, -85.52376, -85.52366, -...
name                                                    Cherokee
state                                                         al

                                     ...                          \
                                     ...
detailed name                        ...
lats                                 ...
lons                                 ...
name                                 ...
state                                ...

                                                              60  \
                                                             50
detailed name                   Western District, American Samoa
lats           [-14.27863, -14.29046, -14.29182, -14.30005, -...
lons           [-170.76068, -170.74639, -170.74476, -170.7343...
name                                                     Western
state                                                         as

                                                                  \
                                                             30
detailed name                        Rose Island, American Samoa
lats           [-14.60181, -14.60134, -14.5998, -14.59707, -1...
lons           [-168.15785, -168.17354, -168.18133, -168.1951...
name                                                 Rose Island
state                                                         as

                                                              78  \
                                                             10
detailed name                   St. Croix Island, Virgin Islands
lats           [17.82788, 17.83758, 17.84488, 17.84398, 17.83...
lons           [-64.67724, -64.6634, -64.63888, -64.61519, -6...
name                                                   St. Croix
state                                                         vi

                                                              66  \
                                                             10
detailed name                                         Guam, Guam
lats           [13.25, 13.24265, 13.23614, 13.22532, 13.21018...
lons           [144.80012, 144.79333, 144.78547, 144.77834, 1...
name                                                        Guam
state                                                         gu

                                                              69  \
                                                             110
detailed name               Saipan Municipality, Mariana Islands
lats           [15.06592, 15.023, 15.02291, 15.05119, 15.0518...
lons           [145.75, 145.74419, 145.74416, 145.70731, 145....
name                                                      Saipan
state                                                         mp

                                                                  \
                                                             120
detailed name               Tinian Municipality, Mariana Islands
lats           [15.08725, 15.08921, 15.08928, 15.12502, 15.11...
lons           [145.53396, 145.53502, 145.53508, 145.5726, 14...
name                                                      Tinian
state                                                         mp

                                                                  \
                                                             85
detailed name     Northern Islands Municipality, Mariana Islands
lats           [16.28054, 16.28936, 16.30034, 16.30581, 16.34...
lons           [145.625, 145.6038, 145.58463, 145.57507, 145....
name                                            Northern Islands
state                                                         mp

                                                                  \
                                                             100
detailed name                 Rota Municipality, Mariana Islands
lats           [14.125, 14.1379, 14.13894, 14.15911, 14.16874...
lons           [145.05897, 145.06302, 145.06362, 145.07524, 1...
name                                                        Rota
state                                                         mp

                                                              78  \
                                                             20
detailed name                    St. John Island, Virgin Islands
lats           [18.26736, 18.26127, 18.25615, 18.25413, 18.25...
lons           [-64.6613, -64.66426, -64.67124, -64.67492, -6...
name                                                    St. John
state                                                         vi


                                                             30
detailed name                  St. Thomas Island, Virgin Islands
lats           [18.39372, 18.39371, 18.39371, 18.38957, 18.37...
lons           [-64.84592, -64.84417, -64.84373, -64.84373, -...
name                                                  St. Thomas
state                                                         vi

[5 rows x 3233 columns]

## 3.2.3 Construct the graph

In [10]:
palette.reverse()

counties = {
    code: county for code, county in counties.items() if county["state"] == "tx"
}

county_xs = [county["lons"] for county in counties.values()]
county_ys = [county["lats"] for county in counties.values()]

county_names = [county['name'] for county in counties.values()]
county_rates = [unemployment[county_id] for county_id in counties]
color_mapper = LogColorMapper(palette=palette)

source = ColumnDataSource(data=dict(
    x=county_xs,
    y=county_ys,
    name=county_names,
    rate=county_rates,
))

TOOLS = "pan,wheel_zoom,reset,hover,save"

p = figure(
    title="Texas Unemployment, 2009", tools=TOOLS,
    x_axis_location=None, y_axis_location=None
)
p.grid.grid_line_color = None

p.patches('x', 'y', source=source,
          fill_color={'field': 'rate', 'transform': color_mapper},
          fill_alpha=0.7, line_color="white", line_width=0.5)

hover = p.select_one(HoverTool)
hover.point_policy = "follow_mouse"
hover.tooltips = [
    ("Name", "@name"),
    ("Unemployment rate)", "@rate%"),
    ("(Long, Lat)", "($x, $y)"),
]

show(p)